# Generated by Django 4.1.5 on 2023-09-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_basket_basketitem_basket_items_basket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='quantity',
        ),
    ]
